name: Test Project

on: push

jobs:
  test:
    # See pre-installed software on GitHub-hosted runners.
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#preinstalled-software
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        # Lock in a specific version to avoid breaking changes
        uses: actions/checkout@v4
        # Action configuration
        # with:
          # Optional. Default: this repository
          # repository: ''
        # NodeJS is pre-installed in ubuntu-latest, but still added to the steps for practice
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        # npm ci installs dependencies based on package-lock.json
        # which ensures alignment with development
        run: npm ci
      - name: Run tests
        run: npm test
